package com.m2m.mapper;

import com.m2m.domain.AdBanner;
import com.m2m.domain.AdBannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AdBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_banner
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(AdBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_banner
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(AdBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_banner
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from ad_banner",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_banner
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into ad_banner (id, ad_banner_name, ",
        "banner_position, ad_banner_height, ",
        "ad_banner_width, status, ",
        "type, create_time)",
        "values (#{id,jdbcType=BIGINT}, #{adBannerName,jdbcType=VARCHAR}, ",
        "#{bannerPosition,jdbcType=VARCHAR}, #{adBannerHeight,jdbcType=INTEGER}, ",
        "#{adBannerWidth,jdbcType=INTEGER}, #{status,jdbcType=INTEGER}, ",
        "#{type,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(AdBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_banner
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(AdBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_banner
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<AdBanner> selectByExample(AdBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_banner
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, ad_banner_name, banner_position, ad_banner_height, ad_banner_width, status, ",
        "type, create_time",
        "from ad_banner",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.m2m.mapper.AdBannerMapper.BaseResultMap")
    AdBanner selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_banner
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") AdBanner record, @Param("example") AdBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_banner
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") AdBanner record, @Param("example") AdBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_banner
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(AdBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_banner
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update ad_banner",
        "set ad_banner_name = #{adBannerName,jdbcType=VARCHAR},",
          "banner_position = #{bannerPosition,jdbcType=VARCHAR},",
          "ad_banner_height = #{adBannerHeight,jdbcType=INTEGER},",
          "ad_banner_width = #{adBannerWidth,jdbcType=INTEGER},",
          "status = #{status,jdbcType=INTEGER},",
          "type = #{type,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AdBanner record);
}