package com.m2m.mapper;

import com.m2m.domain.AdTag;
import com.m2m.domain.AdTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AdTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(AdTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(AdTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from ad_tag",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into ad_tag (id, tag_id, ",
        "banner_id, position, ",
        "create_time)",
        "values (#{id,jdbcType=BIGINT}, #{tagId,jdbcType=BIGINT}, ",
        "#{bannerId,jdbcType=BIGINT}, #{position,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(AdTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(AdTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<AdTag> selectByExample(AdTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, tag_id, banner_id, position, create_time",
        "from ad_tag",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.m2m.mapper.AdTagMapper.BaseResultMap")
    AdTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") AdTag record, @Param("example") AdTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") AdTag record, @Param("example") AdTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(AdTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update ad_tag",
        "set tag_id = #{tagId,jdbcType=BIGINT},",
          "banner_id = #{bannerId,jdbcType=BIGINT},",
          "position = #{position,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AdTag record);
}