package com.m2m.mapper;

import com.m2m.domain.AppConfig;
import com.m2m.domain.AppConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AppConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(AppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(AppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from app_config",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into app_config (id, name, ",
        "config_key, config_value, ",
        "type_name)",
        "values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{configKey,jdbcType=VARCHAR}, #{configValue,jdbcType=VARCHAR}, ",
        "#{typeName,jdbcType=VARCHAR})"
    })
    int insert(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<AppConfig> selectByExample(AppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, name, config_key, config_value, type_name",
        "from app_config",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.m2m.mapper.AppConfigMapper.BaseResultMap")
    AppConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") AppConfig record, @Param("example") AppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") AppConfig record, @Param("example") AppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update app_config",
        "set name = #{name,jdbcType=VARCHAR},",
          "config_key = #{configKey,jdbcType=VARCHAR},",
          "config_value = #{configValue,jdbcType=VARCHAR},",
          "type_name = #{typeName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AppConfig record);
}