package com.m2m.mapper;

import com.m2m.domain.AppLightboxSource;
import com.m2m.domain.AppLightboxSourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AppLightboxSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(AppLightboxSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(AppLightboxSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from app_lightbox_source",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into app_lightbox_source (id, image, ",
        "main_text, secondary_text, ",
        "main_tone, link_url, ",
        "start_time, end_time, ",
        "status)",
        "values (#{id,jdbcType=BIGINT}, #{image,jdbcType=VARCHAR}, ",
        "#{mainText,jdbcType=VARCHAR}, #{secondaryText,jdbcType=VARCHAR}, ",
        "#{mainTone,jdbcType=VARCHAR}, #{linkUrl,jdbcType=VARCHAR}, ",
        "#{startTime,jdbcType=TIMESTAMP}, #{endTime,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=INTEGER})"
    })
    int insert(AppLightboxSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(AppLightboxSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<AppLightboxSource> selectByExample(AppLightboxSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, image, main_text, secondary_text, main_tone, link_url, start_time, end_time, ",
        "status",
        "from app_lightbox_source",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.m2m.mapper.AppLightboxSourceMapper.BaseResultMap")
    AppLightboxSource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") AppLightboxSource record, @Param("example") AppLightboxSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") AppLightboxSource record, @Param("example") AppLightboxSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(AppLightboxSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update app_lightbox_source",
        "set image = #{image,jdbcType=VARCHAR},",
          "main_text = #{mainText,jdbcType=VARCHAR},",
          "secondary_text = #{secondaryText,jdbcType=VARCHAR},",
          "main_tone = #{mainTone,jdbcType=VARCHAR},",
          "link_url = #{linkUrl,jdbcType=VARCHAR},",
          "start_time = #{startTime,jdbcType=TIMESTAMP},",
          "end_time = #{endTime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AppLightboxSource record);
}