package com.m2m.mapper;

import com.m2m.domain.BillBoard;
import com.m2m.domain.BillBoardExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BillBoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(BillBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(BillBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from billboard",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into billboard (id, type, ",
        "name, summary, bg_color, ",
        "image, img_width, ",
        "img_height, show_name, ",
        "create_time, update_time, ",
        "status, mode)",
        "values (#{id,jdbcType=BIGINT}, #{type,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{summary,jdbcType=VARCHAR}, #{bgColor,jdbcType=VARCHAR}, ",
        "#{image,jdbcType=VARCHAR}, #{imgWidth,jdbcType=INTEGER}, ",
        "#{imgHeight,jdbcType=INTEGER}, #{showName,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=INTEGER}, #{mode,jdbcType=INTEGER})"
    })
    int insert(BillBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(BillBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<BillBoard> selectByExample(BillBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, type, name, summary, bg_color, image, img_width, img_height, show_name, ",
        "create_time, update_time, status, mode",
        "from billboard",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.m2m.mapper.BillBoardMapper.BaseResultMap")
    BillBoard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") BillBoard record, @Param("example") BillBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") BillBoard record, @Param("example") BillBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(BillBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update billboard",
        "set type = #{type,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "summary = #{summary,jdbcType=VARCHAR},",
          "bg_color = #{bgColor,jdbcType=VARCHAR},",
          "image = #{image,jdbcType=VARCHAR},",
          "img_width = #{imgWidth,jdbcType=INTEGER},",
          "img_height = #{imgHeight,jdbcType=INTEGER},",
          "show_name = #{showName,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=INTEGER},",
          "mode = #{mode,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BillBoard record);
}