package com.m2m.mapper;

import com.m2m.domain.BillboardDetails;
import com.m2m.domain.BillboardDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BillboardDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_details
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(BillboardDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_details
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(BillboardDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_details
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from billboard_details",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_details
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into billboard_details (id, type, ",
        "bid, sort, status)",
        "values (#{id,jdbcType=BIGINT}, #{type,jdbcType=INTEGER}, ",
        "#{bid,jdbcType=BIGINT}, #{sort,jdbcType=INTEGER}, #{status,jdbcType=INTEGER})"
    })
    int insert(BillboardDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_details
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(BillboardDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_details
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<BillboardDetails> selectByExample(BillboardDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_details
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, type, bid, sort, status",
        "from billboard_details",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.m2m.mapper.BillboardDetailsMapper.BaseResultMap")
    BillboardDetails selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_details
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") BillboardDetails record, @Param("example") BillboardDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_details
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") BillboardDetails record, @Param("example") BillboardDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_details
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(BillboardDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_details
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update billboard_details",
        "set type = #{type,jdbcType=INTEGER},",
          "bid = #{bid,jdbcType=BIGINT},",
          "sort = #{sort,jdbcType=INTEGER},",
          "status = #{status,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BillboardDetails record);
}