package com.m2m.mapper;

import com.m2m.domain.CmsFeatureGroup;
import com.m2m.domain.CmsFeatureGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CmsFeatureGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature_group
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(CmsFeatureGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature_group
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(CmsFeatureGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature_group
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from cms_feature_group",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature_group
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into cms_feature_group (id, name, ",
        "created_at)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(CmsFeatureGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature_group
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(CmsFeatureGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature_group
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<CmsFeatureGroup> selectByExample(CmsFeatureGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature_group
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, name, created_at",
        "from cms_feature_group",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.m2m.mapper.CmsFeatureGroupMapper.BaseResultMap")
    CmsFeatureGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature_group
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") CmsFeatureGroup record, @Param("example") CmsFeatureGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature_group
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") CmsFeatureGroup record, @Param("example") CmsFeatureGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature_group
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(CmsFeatureGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature_group
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update cms_feature_group",
        "set name = #{name,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CmsFeatureGroup record);
}