package com.m2m.mapper;

import com.m2m.domain.CmsFeature;
import com.m2m.domain.CmsFeatureExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CmsFeatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(CmsFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(CmsFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from cms_feature",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into cms_feature (id, feature_group_id, ",
        "name, created_at)",
        "values (#{id,jdbcType=INTEGER}, #{featureGroupId,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(CmsFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(CmsFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<CmsFeature> selectByExample(CmsFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, feature_group_id, name, created_at",
        "from cms_feature",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.m2m.mapper.CmsFeatureMapper.BaseResultMap")
    CmsFeature selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") CmsFeature record, @Param("example") CmsFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") CmsFeature record, @Param("example") CmsFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(CmsFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update cms_feature",
        "set feature_group_id = #{featureGroupId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CmsFeature record);
}