package com.m2m.mapper;

import com.m2m.domain.CmsUserFeature;
import com.m2m.domain.CmsUserFeatureExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CmsUserFeatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(CmsUserFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(CmsUserFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from cms_user_feature",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into cms_user_feature (id, user_id, ",
        "feature_id, status, created_at)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{featureId,jdbcType=INTEGER}, #{status,jdbcType=BIT}, #{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(CmsUserFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(CmsUserFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<CmsUserFeature> selectByExample(CmsUserFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, user_id, feature_id, status, created_at",
        "from cms_user_feature",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.m2m.mapper.CmsUserFeatureMapper.BaseResultMap")
    CmsUserFeature selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") CmsUserFeature record, @Param("example") CmsUserFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") CmsUserFeature record, @Param("example") CmsUserFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(CmsUserFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_feature
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update cms_user_feature",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "feature_id = #{featureId,jdbcType=INTEGER},",
          "status = #{status,jdbcType=BIT},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CmsUserFeature record);
}