package com.m2m.mapper;

import com.m2m.domain.CmsUserLog;
import com.m2m.domain.CmsUserLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CmsUserLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_log
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(CmsUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_log
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(CmsUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_log
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from cms_user_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_log
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into cms_user_log (id, user_id, ",
        "feature_id, created_at)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{featureId,jdbcType=INTEGER}, #{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(CmsUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_log
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(CmsUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_log
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<CmsUserLog> selectByExample(CmsUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_log
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, user_id, feature_id, created_at",
        "from cms_user_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.m2m.mapper.CmsUserLogMapper.BaseResultMap")
    CmsUserLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_log
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") CmsUserLog record, @Param("example") CmsUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_log
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") CmsUserLog record, @Param("example") CmsUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_log
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(CmsUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_log
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update cms_user_log",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "feature_id = #{featureId,jdbcType=INTEGER},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CmsUserLog record);
}