package com.m2m.mapper;

import com.m2m.domain.EmotionPackDetail;
import com.m2m.domain.EmotionPackDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface EmotionPackDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack_detail
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(EmotionPackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack_detail
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(EmotionPackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack_detail
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from emotion_pack_detail",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack_detail
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into emotion_pack_detail (id, pack_id, ",
        "title, image, thumb, ",
        "w, h, thumb_w, ",
        "thumb_h, extra, order_num)",
        "values (#{id,jdbcType=INTEGER}, #{packId,jdbcType=INTEGER}, ",
        "#{title,jdbcType=VARCHAR}, #{image,jdbcType=VARCHAR}, #{thumb,jdbcType=VARCHAR}, ",
        "#{w,jdbcType=INTEGER}, #{h,jdbcType=INTEGER}, #{thumbW,jdbcType=INTEGER}, ",
        "#{thumbH,jdbcType=INTEGER}, #{extra,jdbcType=VARCHAR}, #{orderNum,jdbcType=INTEGER})"
    })
    int insert(EmotionPackDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack_detail
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(EmotionPackDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack_detail
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<EmotionPackDetail> selectByExample(EmotionPackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack_detail
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, pack_id, title, image, thumb, w, h, thumb_w, thumb_h, extra, order_num",
        "from emotion_pack_detail",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.m2m.mapper.EmotionPackDetailMapper.BaseResultMap")
    EmotionPackDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack_detail
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") EmotionPackDetail record, @Param("example") EmotionPackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack_detail
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") EmotionPackDetail record, @Param("example") EmotionPackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack_detail
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(EmotionPackDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack_detail
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update emotion_pack_detail",
        "set pack_id = #{packId,jdbcType=INTEGER},",
          "title = #{title,jdbcType=VARCHAR},",
          "image = #{image,jdbcType=VARCHAR},",
          "thumb = #{thumb,jdbcType=VARCHAR},",
          "w = #{w,jdbcType=INTEGER},",
          "h = #{h,jdbcType=INTEGER},",
          "thumb_w = #{thumbW,jdbcType=INTEGER},",
          "thumb_h = #{thumbH,jdbcType=INTEGER},",
          "extra = #{extra,jdbcType=VARCHAR},",
          "order_num = #{orderNum,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(EmotionPackDetail record);
}