package com.m2m.mapper;

import com.m2m.domain.GiftInfo;
import com.m2m.domain.GiftInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface GiftInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_info
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(GiftInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_info
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(GiftInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_info
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from gift_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_info
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into gift_info (id, name, ",
        "image, price, add_price, ",
        "image_width, image_height, ",
        "gif_image, play_time, ",
        "sort_number, status, ",
        "create_time)",
        "values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{image,jdbcType=VARCHAR}, #{price,jdbcType=INTEGER}, #{addPrice,jdbcType=INTEGER}, ",
        "#{imageWidth,jdbcType=INTEGER}, #{imageHeight,jdbcType=INTEGER}, ",
        "#{gifImage,jdbcType=VARCHAR}, #{playTime,jdbcType=INTEGER}, ",
        "#{sortNumber,jdbcType=INTEGER}, #{status,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(GiftInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_info
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(GiftInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_info
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<GiftInfo> selectByExample(GiftInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_info
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, name, image, price, add_price, image_width, image_height, gif_image, play_time, ",
        "sort_number, status, create_time",
        "from gift_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.m2m.mapper.GiftInfoMapper.BaseResultMap")
    GiftInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_info
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") GiftInfo record, @Param("example") GiftInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_info
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") GiftInfo record, @Param("example") GiftInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_info
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(GiftInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_info
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update gift_info",
        "set name = #{name,jdbcType=VARCHAR},",
          "image = #{image,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=INTEGER},",
          "add_price = #{addPrice,jdbcType=INTEGER},",
          "image_width = #{imageWidth,jdbcType=INTEGER},",
          "image_height = #{imageHeight,jdbcType=INTEGER},",
          "gif_image = #{gifImage,jdbcType=VARCHAR},",
          "play_time = #{playTime,jdbcType=INTEGER},",
          "sort_number = #{sortNumber,jdbcType=INTEGER},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(GiftInfo record);
}