package com.m2m.mapper;

import com.m2m.domain.KingdomCountDay;
import com.m2m.domain.KingdomCountDayExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface KingdomCountDayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingdom_count_day
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(KingdomCountDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingdom_count_day
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(KingdomCountDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingdom_count_day
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from kingdom_count_day",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingdom_count_day
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into kingdom_count_day (id, refresh_date, ",
        "content_type, forward_cid, ",
        "person_count, review_count, ",
        "like_count, favorite_count, ",
        "read_count, read_count_dummy, ",
        "title, create_time, ",
        "update_time, type, ",
        "live_image, uid, ",
        "nick_name, v_lv, avatar, ",
        "topic_id, textCount, ",
        "imgCount, videoCount, ",
        "audioCount, updateCount)",
        "values (#{id,jdbcType=INTEGER}, #{refreshDate,jdbcType=TIMESTAMP}, ",
        "#{contentType,jdbcType=INTEGER}, #{forwardCid,jdbcType=INTEGER}, ",
        "#{personCount,jdbcType=INTEGER}, #{reviewCount,jdbcType=INTEGER}, ",
        "#{likeCount,jdbcType=INTEGER}, #{favoriteCount,jdbcType=INTEGER}, ",
        "#{readCount,jdbcType=INTEGER}, #{readCountDummy,jdbcType=INTEGER}, ",
        "#{title,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{type,jdbcType=INTEGER}, ",
        "#{liveImage,jdbcType=VARCHAR}, #{uid,jdbcType=INTEGER}, ",
        "#{nickName,jdbcType=VARCHAR}, #{vLv,jdbcType=INTEGER}, #{avatar,jdbcType=VARCHAR}, ",
        "#{topicId,jdbcType=INTEGER}, #{textcount,jdbcType=INTEGER}, ",
        "#{imgcount,jdbcType=INTEGER}, #{videocount,jdbcType=INTEGER}, ",
        "#{audiocount,jdbcType=INTEGER}, #{updatecount,jdbcType=INTEGER})"
    })
    int insert(KingdomCountDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingdom_count_day
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(KingdomCountDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingdom_count_day
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<KingdomCountDay> selectByExample(KingdomCountDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingdom_count_day
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, refresh_date, content_type, forward_cid, person_count, review_count, like_count, ",
        "favorite_count, read_count, read_count_dummy, title, create_time, update_time, ",
        "type, live_image, uid, nick_name, v_lv, avatar, topic_id, textCount, imgCount, ",
        "videoCount, audioCount, updateCount",
        "from kingdom_count_day",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.m2m.mapper.KingdomCountDayMapper.BaseResultMap")
    KingdomCountDay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingdom_count_day
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") KingdomCountDay record, @Param("example") KingdomCountDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingdom_count_day
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") KingdomCountDay record, @Param("example") KingdomCountDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingdom_count_day
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(KingdomCountDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingdom_count_day
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update kingdom_count_day",
        "set refresh_date = #{refreshDate,jdbcType=TIMESTAMP},",
          "content_type = #{contentType,jdbcType=INTEGER},",
          "forward_cid = #{forwardCid,jdbcType=INTEGER},",
          "person_count = #{personCount,jdbcType=INTEGER},",
          "review_count = #{reviewCount,jdbcType=INTEGER},",
          "like_count = #{likeCount,jdbcType=INTEGER},",
          "favorite_count = #{favoriteCount,jdbcType=INTEGER},",
          "read_count = #{readCount,jdbcType=INTEGER},",
          "read_count_dummy = #{readCountDummy,jdbcType=INTEGER},",
          "title = #{title,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "type = #{type,jdbcType=INTEGER},",
          "live_image = #{liveImage,jdbcType=VARCHAR},",
          "uid = #{uid,jdbcType=INTEGER},",
          "nick_name = #{nickName,jdbcType=VARCHAR},",
          "v_lv = #{vLv,jdbcType=INTEGER},",
          "avatar = #{avatar,jdbcType=VARCHAR},",
          "topic_id = #{topicId,jdbcType=INTEGER},",
          "textCount = #{textcount,jdbcType=INTEGER},",
          "imgCount = #{imgcount,jdbcType=INTEGER},",
          "videoCount = #{videocount,jdbcType=INTEGER},",
          "audioCount = #{audiocount,jdbcType=INTEGER},",
          "updateCount = #{updatecount,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(KingdomCountDay record);
}