package com.m2m.mapper;

import com.m2m.domain.LotteryAppoint;
import com.m2m.domain.LotteryAppointExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface LotteryAppointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_appoint
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(LotteryAppointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_appoint
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(LotteryAppointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_appoint
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from lottery_appoint",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_appoint
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into lottery_appoint (id, lottery_id, ",
        "uid, create_time)",
        "values (#{id,jdbcType=BIGINT}, #{lotteryId,jdbcType=BIGINT}, ",
        "#{uid,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(LotteryAppoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_appoint
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(LotteryAppoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_appoint
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<LotteryAppoint> selectByExample(LotteryAppointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_appoint
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, lottery_id, uid, create_time",
        "from lottery_appoint",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.m2m.mapper.LotteryAppointMapper.BaseResultMap")
    LotteryAppoint selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_appoint
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") LotteryAppoint record, @Param("example") LotteryAppointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_appoint
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") LotteryAppoint record, @Param("example") LotteryAppointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_appoint
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(LotteryAppoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_appoint
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update lottery_appoint",
        "set lottery_id = #{lotteryId,jdbcType=BIGINT},",
          "uid = #{uid,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(LotteryAppoint record);
}