package com.m2m.mapper;

import com.m2m.domain.TopicFragment;
import com.m2m.domain.TopicFragmentExample;
import com.m2m.domain.TopicFragmentWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TopicFragmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(TopicFragmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(TopicFragmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from topic_fragment",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into topic_fragment (id, topic_id, ",
        "uid, fragment_image, ",
        "type, content_type, ",
        "top_id, bottom_id, create_time, ",
        "at_uid, source, score, ",
        "status, update_time, ",
        "out_type, fragment, ",
        "extra)",
        "values (#{id,jdbcType=BIGINT}, #{topicId,jdbcType=BIGINT}, ",
        "#{uid,jdbcType=BIGINT}, #{fragmentImage,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=INTEGER}, #{contentType,jdbcType=INTEGER}, ",
        "#{topId,jdbcType=BIGINT}, #{bottomId,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{atUid,jdbcType=BIGINT}, #{source,jdbcType=INTEGER}, #{score,jdbcType=INTEGER}, ",
        "#{status,jdbcType=INTEGER}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{outType,jdbcType=INTEGER}, #{fragment,jdbcType=LONGVARCHAR}, ",
        "#{extra,jdbcType=LONGVARCHAR})"
    })
    int insert(TopicFragmentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(TopicFragmentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<TopicFragmentWithBLOBs> selectByExampleWithBLOBs(TopicFragmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<TopicFragment> selectByExample(TopicFragmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, topic_id, uid, fragment_image, type, content_type, top_id, bottom_id, create_time, ",
        "at_uid, source, score, status, update_time, out_type, fragment, extra",
        "from topic_fragment",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.m2m.mapper.TopicFragmentMapper.ResultMapWithBLOBs")
    TopicFragmentWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") TopicFragmentWithBLOBs record, @Param("example") TopicFragmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") TopicFragmentWithBLOBs record, @Param("example") TopicFragmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") TopicFragment record, @Param("example") TopicFragmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(TopicFragmentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update topic_fragment",
        "set topic_id = #{topicId,jdbcType=BIGINT},",
          "uid = #{uid,jdbcType=BIGINT},",
          "fragment_image = #{fragmentImage,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "content_type = #{contentType,jdbcType=INTEGER},",
          "top_id = #{topId,jdbcType=BIGINT},",
          "bottom_id = #{bottomId,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "at_uid = #{atUid,jdbcType=BIGINT},",
          "source = #{source,jdbcType=INTEGER},",
          "score = #{score,jdbcType=INTEGER},",
          "status = #{status,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "out_type = #{outType,jdbcType=INTEGER},",
          "fragment = #{fragment,jdbcType=LONGVARCHAR},",
          "extra = #{extra,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(TopicFragmentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update topic_fragment",
        "set topic_id = #{topicId,jdbcType=BIGINT},",
          "uid = #{uid,jdbcType=BIGINT},",
          "fragment_image = #{fragmentImage,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "content_type = #{contentType,jdbcType=INTEGER},",
          "top_id = #{topId,jdbcType=BIGINT},",
          "bottom_id = #{bottomId,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "at_uid = #{atUid,jdbcType=BIGINT},",
          "source = #{source,jdbcType=INTEGER},",
          "score = #{score,jdbcType=INTEGER},",
          "status = #{status,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "out_type = #{outType,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TopicFragment record);
}