package com.m2m.mapper;

import com.m2m.domain.TopicListed;
import com.m2m.domain.TopicListedExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TopicListedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_listed
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(TopicListedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_listed
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(TopicListedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_listed
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from topic_listed",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_listed
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into topic_listed (id, topic_id, ",
        "person_count, review_count, ",
        "read_count, price, ",
        "price_RMB, buy_uid, ",
        "buy_time, status, ",
        "create_time)",
        "values (#{id,jdbcType=BIGINT}, #{topicId,jdbcType=BIGINT}, ",
        "#{personCount,jdbcType=INTEGER}, #{reviewCount,jdbcType=INTEGER}, ",
        "#{readCount,jdbcType=INTEGER}, #{price,jdbcType=INTEGER}, ",
        "#{priceRmb,jdbcType=DOUBLE}, #{buyUid,jdbcType=BIGINT}, ",
        "#{buyTime,jdbcType=TIMESTAMP}, #{status,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(TopicListed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_listed
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(TopicListed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_listed
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<TopicListed> selectByExample(TopicListedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_listed
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, topic_id, person_count, review_count, read_count, price, price_RMB, buy_uid, ",
        "buy_time, status, create_time",
        "from topic_listed",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.m2m.mapper.TopicListedMapper.BaseResultMap")
    TopicListed selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_listed
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") TopicListed record, @Param("example") TopicListedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_listed
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") TopicListed record, @Param("example") TopicListedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_listed
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(TopicListed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_listed
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update topic_listed",
        "set topic_id = #{topicId,jdbcType=BIGINT},",
          "person_count = #{personCount,jdbcType=INTEGER},",
          "review_count = #{reviewCount,jdbcType=INTEGER},",
          "read_count = #{readCount,jdbcType=INTEGER},",
          "price = #{price,jdbcType=INTEGER},",
          "price_RMB = #{priceRmb,jdbcType=DOUBLE},",
          "buy_uid = #{buyUid,jdbcType=BIGINT},",
          "buy_time = #{buyTime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TopicListed record);
}