package com.m2m.mapper;

import com.m2m.domain.Topic;
import com.m2m.domain.TopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from topic",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into topic (id, uid, live_image, ",
        "title, status, create_time, ",
        "update_time, long_time, ",
        "qrcode, core_circle, ",
        "type, ce_audit_type, ",
        "ac_audit_type, ac_publish_type, ",
        "rights, summary, ",
        "sub_type, price, ",
        "listing_time, out_time, ",
        "category_id, auto_join_core, ",
        "only_friend)",
        "values (#{id,jdbcType=BIGINT}, #{uid,jdbcType=BIGINT}, #{liveImage,jdbcType=VARCHAR}, ",
        "#{title,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{longTime,jdbcType=BIGINT}, ",
        "#{qrcode,jdbcType=VARCHAR}, #{coreCircle,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=INTEGER}, #{ceAuditType,jdbcType=INTEGER}, ",
        "#{acAuditType,jdbcType=INTEGER}, #{acPublishType,jdbcType=INTEGER}, ",
        "#{rights,jdbcType=INTEGER}, #{summary,jdbcType=VARCHAR}, ",
        "#{subType,jdbcType=INTEGER}, #{price,jdbcType=INTEGER}, ",
        "#{listingTime,jdbcType=TIMESTAMP}, #{outTime,jdbcType=TIMESTAMP}, ",
        "#{categoryId,jdbcType=INTEGER}, #{autoJoinCore,jdbcType=INTEGER}, ",
        "#{onlyFriend,jdbcType=INTEGER})"
    })
    int insert(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<Topic> selectByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, uid, live_image, title, status, create_time, update_time, long_time, qrcode, ",
        "core_circle, type, ce_audit_type, ac_audit_type, ac_publish_type, rights, summary, ",
        "sub_type, price, listing_time, out_time, category_id, auto_join_core, only_friend",
        "from topic",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.m2m.mapper.TopicMapper.BaseResultMap")
    Topic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") Topic record, @Param("example") TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") Topic record, @Param("example") TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update topic",
        "set uid = #{uid,jdbcType=BIGINT},",
          "live_image = #{liveImage,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "long_time = #{longTime,jdbcType=BIGINT},",
          "qrcode = #{qrcode,jdbcType=VARCHAR},",
          "core_circle = #{coreCircle,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "ce_audit_type = #{ceAuditType,jdbcType=INTEGER},",
          "ac_audit_type = #{acAuditType,jdbcType=INTEGER},",
          "ac_publish_type = #{acPublishType,jdbcType=INTEGER},",
          "rights = #{rights,jdbcType=INTEGER},",
          "summary = #{summary,jdbcType=VARCHAR},",
          "sub_type = #{subType,jdbcType=INTEGER},",
          "price = #{price,jdbcType=INTEGER},",
          "listing_time = #{listingTime,jdbcType=TIMESTAMP},",
          "out_time = #{outTime,jdbcType=TIMESTAMP},",
          "category_id = #{categoryId,jdbcType=INTEGER},",
          "auto_join_core = #{autoJoinCore,jdbcType=INTEGER},",
          "only_friend = #{onlyFriend,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Topic record);
}