package com.m2m.mapper;

import com.m2m.domain.TopicTag;
import com.m2m.domain.TopicTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TopicTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(TopicTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(TopicTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from topic_tag",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into topic_tag (id, tag, ",
        "is_rec, is_sys, status, ",
        "create_time, user_hobby_ids, ",
        "pid, order_num, cover_img)",
        "values (#{id,jdbcType=BIGINT}, #{tag,jdbcType=VARCHAR}, ",
        "#{isRec,jdbcType=INTEGER}, #{isSys,jdbcType=INTEGER}, #{status,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{userHobbyIds,jdbcType=VARCHAR}, ",
        "#{pid,jdbcType=INTEGER}, #{orderNum,jdbcType=INTEGER}, #{coverImg,jdbcType=VARCHAR})"
    })
    int insert(TopicTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(TopicTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<TopicTag> selectByExample(TopicTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, tag, is_rec, is_sys, status, create_time, user_hobby_ids, pid, order_num, ",
        "cover_img",
        "from topic_tag",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.m2m.mapper.TopicTagMapper.BaseResultMap")
    TopicTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") TopicTag record, @Param("example") TopicTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") TopicTag record, @Param("example") TopicTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(TopicTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_tag
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update topic_tag",
        "set tag = #{tag,jdbcType=VARCHAR},",
          "is_rec = #{isRec,jdbcType=INTEGER},",
          "is_sys = #{isSys,jdbcType=INTEGER},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "user_hobby_ids = #{userHobbyIds,jdbcType=VARCHAR},",
          "pid = #{pid,jdbcType=INTEGER},",
          "order_num = #{orderNum,jdbcType=INTEGER},",
          "cover_img = #{coverImg,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TopicTag record);
}