package com.m2m.mapper;

import com.m2m.domain.UserNo;
import com.m2m.domain.UserNoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserNoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_no
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(UserNoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_no
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(UserNoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_no
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from user_no",
        "where uid = #{uid,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_no
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into user_no (uid, me_number)",
        "values (#{uid,jdbcType=BIGINT}, #{meNumber,jdbcType=BIGINT})"
    })
    int insert(UserNo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_no
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(UserNo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_no
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<UserNo> selectByExample(UserNoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_no
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "uid, me_number",
        "from user_no",
        "where uid = #{uid,jdbcType=BIGINT}"
    })
    @ResultMap("com.m2m.mapper.UserNoMapper.BaseResultMap")
    UserNo selectByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_no
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserNo record, @Param("example") UserNoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_no
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") UserNo record, @Param("example") UserNoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_no
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(UserNo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_no
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update user_no",
        "set me_number = #{meNumber,jdbcType=BIGINT}",
        "where uid = #{uid,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserNo record);
}