package com.m2m.mapper;

import com.m2m.domain.UserIndustry;
import com.m2m.domain.UserIndustryExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserIndustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(UserIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(UserIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from user_industry",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into user_industry (id, industry_name, ",
        "cover_img, industry_description, ",
        "create_time, update_time, ",
        "sort)",
        "values (#{id,jdbcType=BIGINT}, #{industryName,jdbcType=VARCHAR}, ",
        "#{coverImg,jdbcType=VARCHAR}, #{industryDescription,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{sort,jdbcType=INTEGER})"
    })
    int insert(UserIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(UserIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<UserIndustry> selectByExample(UserIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, industry_name, cover_img, industry_description, create_time, update_time, ",
        "sort",
        "from user_industry",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.m2m.mapper.UserIndustryMapper.BaseResultMap")
    UserIndustry selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserIndustry record, @Param("example") UserIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") UserIndustry record, @Param("example") UserIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(UserIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update user_industry",
        "set industry_name = #{industryName,jdbcType=VARCHAR},",
          "cover_img = #{coverImg,jdbcType=VARCHAR},",
          "industry_description = #{industryDescription,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "sort = #{sort,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserIndustry record);
}