package com.m2m.mapper;

import com.m2m.domain.UserProfile;
import com.m2m.domain.UserProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    long countByExample(UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int deleteByExample(UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Delete({
        "delete from user_profile",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Insert({
        "insert into user_profile (id, uid, mobile, ",
        "nick_name, gender, ",
        "birthday, avatar, ",
        "years_id, star_id, social_class, ",
        "marriage_status, bear_status, ",
        "excellent, introduced, ",
        "create_time, update_time, ",
        "is_promoter, is_activate, ",
        "referee_uid, qrcode, ",
        "third_part_bind, v_lv, ",
        "is_client_login, channel, ",
        "platform, register_version, ",
        "like_gender, age_group, ",
        "occupation, name_group, ",
        "mbti, level, available_coin, ",
        "avatar_frame, industry_id)",
        "values (#{id,jdbcType=BIGINT}, #{uid,jdbcType=BIGINT}, #{mobile,jdbcType=VARCHAR}, ",
        "#{nickName,jdbcType=VARCHAR}, #{gender,jdbcType=INTEGER}, ",
        "#{birthday,jdbcType=VARCHAR}, #{avatar,jdbcType=VARCHAR}, ",
        "#{yearsId,jdbcType=BIGINT}, #{starId,jdbcType=BIGINT}, #{socialClass,jdbcType=BIGINT}, ",
        "#{marriageStatus,jdbcType=BIGINT}, #{bearStatus,jdbcType=BIGINT}, ",
        "#{excellent,jdbcType=INTEGER}, #{introduced,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{isPromoter,jdbcType=INTEGER}, #{isActivate,jdbcType=INTEGER}, ",
        "#{refereeUid,jdbcType=BIGINT}, #{qrcode,jdbcType=VARCHAR}, ",
        "#{thirdPartBind,jdbcType=VARCHAR}, #{vLv,jdbcType=INTEGER}, ",
        "#{isClientLogin,jdbcType=INTEGER}, #{channel,jdbcType=VARCHAR}, ",
        "#{platform,jdbcType=INTEGER}, #{registerVersion,jdbcType=VARCHAR}, ",
        "#{likeGender,jdbcType=INTEGER}, #{ageGroup,jdbcType=INTEGER}, ",
        "#{occupation,jdbcType=INTEGER}, #{nameGroup,jdbcType=VARCHAR}, ",
        "#{mbti,jdbcType=VARCHAR}, #{level,jdbcType=INTEGER}, #{availableCoin,jdbcType=INTEGER}, ",
        "#{avatarFrame,jdbcType=VARCHAR}, #{industryId,jdbcType=BIGINT})"
    })
    int insert(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int insertSelective(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    List<UserProfile> selectByExample(UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Select({
        "select",
        "id, uid, mobile, nick_name, gender, birthday, avatar, years_id, star_id, social_class, ",
        "marriage_status, bear_status, excellent, introduced, create_time, update_time, ",
        "is_promoter, is_activate, referee_uid, qrcode, third_part_bind, v_lv, is_client_login, ",
        "channel, platform, register_version, like_gender, age_group, occupation, name_group, ",
        "mbti, level, available_coin, avatar_frame, industry_id",
        "from user_profile",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.m2m.mapper.UserProfileMapper.BaseResultMap")
    UserProfile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserProfile record, @Param("example") UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByExample(@Param("record") UserProfile record, @Param("example") UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    int updateByPrimaryKeySelective(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    @Update({
        "update user_profile",
        "set uid = #{uid,jdbcType=BIGINT},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "nick_name = #{nickName,jdbcType=VARCHAR},",
          "gender = #{gender,jdbcType=INTEGER},",
          "birthday = #{birthday,jdbcType=VARCHAR},",
          "avatar = #{avatar,jdbcType=VARCHAR},",
          "years_id = #{yearsId,jdbcType=BIGINT},",
          "star_id = #{starId,jdbcType=BIGINT},",
          "social_class = #{socialClass,jdbcType=BIGINT},",
          "marriage_status = #{marriageStatus,jdbcType=BIGINT},",
          "bear_status = #{bearStatus,jdbcType=BIGINT},",
          "excellent = #{excellent,jdbcType=INTEGER},",
          "introduced = #{introduced,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "is_promoter = #{isPromoter,jdbcType=INTEGER},",
          "is_activate = #{isActivate,jdbcType=INTEGER},",
          "referee_uid = #{refereeUid,jdbcType=BIGINT},",
          "qrcode = #{qrcode,jdbcType=VARCHAR},",
          "third_part_bind = #{thirdPartBind,jdbcType=VARCHAR},",
          "v_lv = #{vLv,jdbcType=INTEGER},",
          "is_client_login = #{isClientLogin,jdbcType=INTEGER},",
          "channel = #{channel,jdbcType=VARCHAR},",
          "platform = #{platform,jdbcType=INTEGER},",
          "register_version = #{registerVersion,jdbcType=VARCHAR},",
          "like_gender = #{likeGender,jdbcType=INTEGER},",
          "age_group = #{ageGroup,jdbcType=INTEGER},",
          "occupation = #{occupation,jdbcType=INTEGER},",
          "name_group = #{nameGroup,jdbcType=VARCHAR},",
          "mbti = #{mbti,jdbcType=VARCHAR},",
          "level = #{level,jdbcType=INTEGER},",
          "available_coin = #{availableCoin,jdbcType=INTEGER},",
          "avatar_frame = #{avatarFrame,jdbcType=VARCHAR},",
          "industry_id = #{industryId,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserProfile record);
}