package com.m2m.domain;

import java.util.Date;

public class AdBanner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_banner.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_banner.ad_banner_name
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String adBannerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_banner.banner_position
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String bannerPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_banner.ad_banner_height
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer adBannerHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_banner.ad_banner_width
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer adBannerWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_banner.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_banner.type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_banner.create_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_banner.id
     *
     * @return the value of ad_banner.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_banner.id
     *
     * @param id the value for ad_banner.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_banner.ad_banner_name
     *
     * @return the value of ad_banner.ad_banner_name
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getAdBannerName() {
        return adBannerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_banner.ad_banner_name
     *
     * @param adBannerName the value for ad_banner.ad_banner_name
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setAdBannerName(String adBannerName) {
        this.adBannerName = adBannerName == null ? null : adBannerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_banner.banner_position
     *
     * @return the value of ad_banner.banner_position
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getBannerPosition() {
        return bannerPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_banner.banner_position
     *
     * @param bannerPosition the value for ad_banner.banner_position
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setBannerPosition(String bannerPosition) {
        this.bannerPosition = bannerPosition == null ? null : bannerPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_banner.ad_banner_height
     *
     * @return the value of ad_banner.ad_banner_height
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getAdBannerHeight() {
        return adBannerHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_banner.ad_banner_height
     *
     * @param adBannerHeight the value for ad_banner.ad_banner_height
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setAdBannerHeight(Integer adBannerHeight) {
        this.adBannerHeight = adBannerHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_banner.ad_banner_width
     *
     * @return the value of ad_banner.ad_banner_width
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getAdBannerWidth() {
        return adBannerWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_banner.ad_banner_width
     *
     * @param adBannerWidth the value for ad_banner.ad_banner_width
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setAdBannerWidth(Integer adBannerWidth) {
        this.adBannerWidth = adBannerWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_banner.status
     *
     * @return the value of ad_banner.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_banner.status
     *
     * @param status the value for ad_banner.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_banner.type
     *
     * @return the value of ad_banner.type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_banner.type
     *
     * @param type the value for ad_banner.type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_banner.create_time
     *
     * @return the value of ad_banner.create_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_banner.create_time
     *
     * @param createTime the value for ad_banner.create_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}