package com.m2m.domain;

import java.util.Date;

public class AdInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.ad_title
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String adTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.ad_cover
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String adCover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.ad_cover_width
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer adCoverWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.ad_cover_height
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer adCoverHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.effective_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Date effectiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.create_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.display_probability
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer displayProbability;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.topic_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Long topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.ad_url
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String adUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.banner_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Long bannerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.id
     *
     * @return the value of ad_info.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.id
     *
     * @param id the value for ad_info.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.ad_title
     *
     * @return the value of ad_info.ad_title
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getAdTitle() {
        return adTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.ad_title
     *
     * @param adTitle the value for ad_info.ad_title
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setAdTitle(String adTitle) {
        this.adTitle = adTitle == null ? null : adTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.ad_cover
     *
     * @return the value of ad_info.ad_cover
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getAdCover() {
        return adCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.ad_cover
     *
     * @param adCover the value for ad_info.ad_cover
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setAdCover(String adCover) {
        this.adCover = adCover == null ? null : adCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.ad_cover_width
     *
     * @return the value of ad_info.ad_cover_width
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getAdCoverWidth() {
        return adCoverWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.ad_cover_width
     *
     * @param adCoverWidth the value for ad_info.ad_cover_width
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setAdCoverWidth(Integer adCoverWidth) {
        this.adCoverWidth = adCoverWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.ad_cover_height
     *
     * @return the value of ad_info.ad_cover_height
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getAdCoverHeight() {
        return adCoverHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.ad_cover_height
     *
     * @param adCoverHeight the value for ad_info.ad_cover_height
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setAdCoverHeight(Integer adCoverHeight) {
        this.adCoverHeight = adCoverHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.effective_time
     *
     * @return the value of ad_info.effective_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.effective_time
     *
     * @param effectiveTime the value for ad_info.effective_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.create_time
     *
     * @return the value of ad_info.create_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.create_time
     *
     * @param createTime the value for ad_info.create_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.display_probability
     *
     * @return the value of ad_info.display_probability
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getDisplayProbability() {
        return displayProbability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.display_probability
     *
     * @param displayProbability the value for ad_info.display_probability
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setDisplayProbability(Integer displayProbability) {
        this.displayProbability = displayProbability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.type
     *
     * @return the value of ad_info.type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.type
     *
     * @param type the value for ad_info.type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.topic_id
     *
     * @return the value of ad_info.topic_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.topic_id
     *
     * @param topicId the value for ad_info.topic_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.ad_url
     *
     * @return the value of ad_info.ad_url
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getAdUrl() {
        return adUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.ad_url
     *
     * @param adUrl the value for ad_info.ad_url
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setAdUrl(String adUrl) {
        this.adUrl = adUrl == null ? null : adUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.banner_id
     *
     * @return the value of ad_info.banner_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Long getBannerId() {
        return bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.banner_id
     *
     * @param bannerId the value for ad_info.banner_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setBannerId(Long bannerId) {
        this.bannerId = bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.status
     *
     * @return the value of ad_info.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.status
     *
     * @param status the value for ad_info.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}