package com.m2m.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppLightboxSourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public AppLightboxSourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andImageIsNull() {
            addCriterion("image is null");
            return (Criteria) this;
        }

        public Criteria andImageIsNotNull() {
            addCriterion("image is not null");
            return (Criteria) this;
        }

        public Criteria andImageEqualTo(String value) {
            addCriterion("image =", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotEqualTo(String value) {
            addCriterion("image <>", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThan(String value) {
            addCriterion("image >", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThanOrEqualTo(String value) {
            addCriterion("image >=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThan(String value) {
            addCriterion("image <", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThanOrEqualTo(String value) {
            addCriterion("image <=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLike(String value) {
            addCriterion("image like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotLike(String value) {
            addCriterion("image not like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageIn(List<String> values) {
            addCriterion("image in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotIn(List<String> values) {
            addCriterion("image not in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageBetween(String value1, String value2) {
            addCriterion("image between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotBetween(String value1, String value2) {
            addCriterion("image not between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andMainTextIsNull() {
            addCriterion("main_text is null");
            return (Criteria) this;
        }

        public Criteria andMainTextIsNotNull() {
            addCriterion("main_text is not null");
            return (Criteria) this;
        }

        public Criteria andMainTextEqualTo(String value) {
            addCriterion("main_text =", value, "mainText");
            return (Criteria) this;
        }

        public Criteria andMainTextNotEqualTo(String value) {
            addCriterion("main_text <>", value, "mainText");
            return (Criteria) this;
        }

        public Criteria andMainTextGreaterThan(String value) {
            addCriterion("main_text >", value, "mainText");
            return (Criteria) this;
        }

        public Criteria andMainTextGreaterThanOrEqualTo(String value) {
            addCriterion("main_text >=", value, "mainText");
            return (Criteria) this;
        }

        public Criteria andMainTextLessThan(String value) {
            addCriterion("main_text <", value, "mainText");
            return (Criteria) this;
        }

        public Criteria andMainTextLessThanOrEqualTo(String value) {
            addCriterion("main_text <=", value, "mainText");
            return (Criteria) this;
        }

        public Criteria andMainTextLike(String value) {
            addCriterion("main_text like", value, "mainText");
            return (Criteria) this;
        }

        public Criteria andMainTextNotLike(String value) {
            addCriterion("main_text not like", value, "mainText");
            return (Criteria) this;
        }

        public Criteria andMainTextIn(List<String> values) {
            addCriterion("main_text in", values, "mainText");
            return (Criteria) this;
        }

        public Criteria andMainTextNotIn(List<String> values) {
            addCriterion("main_text not in", values, "mainText");
            return (Criteria) this;
        }

        public Criteria andMainTextBetween(String value1, String value2) {
            addCriterion("main_text between", value1, value2, "mainText");
            return (Criteria) this;
        }

        public Criteria andMainTextNotBetween(String value1, String value2) {
            addCriterion("main_text not between", value1, value2, "mainText");
            return (Criteria) this;
        }

        public Criteria andSecondaryTextIsNull() {
            addCriterion("secondary_text is null");
            return (Criteria) this;
        }

        public Criteria andSecondaryTextIsNotNull() {
            addCriterion("secondary_text is not null");
            return (Criteria) this;
        }

        public Criteria andSecondaryTextEqualTo(String value) {
            addCriterion("secondary_text =", value, "secondaryText");
            return (Criteria) this;
        }

        public Criteria andSecondaryTextNotEqualTo(String value) {
            addCriterion("secondary_text <>", value, "secondaryText");
            return (Criteria) this;
        }

        public Criteria andSecondaryTextGreaterThan(String value) {
            addCriterion("secondary_text >", value, "secondaryText");
            return (Criteria) this;
        }

        public Criteria andSecondaryTextGreaterThanOrEqualTo(String value) {
            addCriterion("secondary_text >=", value, "secondaryText");
            return (Criteria) this;
        }

        public Criteria andSecondaryTextLessThan(String value) {
            addCriterion("secondary_text <", value, "secondaryText");
            return (Criteria) this;
        }

        public Criteria andSecondaryTextLessThanOrEqualTo(String value) {
            addCriterion("secondary_text <=", value, "secondaryText");
            return (Criteria) this;
        }

        public Criteria andSecondaryTextLike(String value) {
            addCriterion("secondary_text like", value, "secondaryText");
            return (Criteria) this;
        }

        public Criteria andSecondaryTextNotLike(String value) {
            addCriterion("secondary_text not like", value, "secondaryText");
            return (Criteria) this;
        }

        public Criteria andSecondaryTextIn(List<String> values) {
            addCriterion("secondary_text in", values, "secondaryText");
            return (Criteria) this;
        }

        public Criteria andSecondaryTextNotIn(List<String> values) {
            addCriterion("secondary_text not in", values, "secondaryText");
            return (Criteria) this;
        }

        public Criteria andSecondaryTextBetween(String value1, String value2) {
            addCriterion("secondary_text between", value1, value2, "secondaryText");
            return (Criteria) this;
        }

        public Criteria andSecondaryTextNotBetween(String value1, String value2) {
            addCriterion("secondary_text not between", value1, value2, "secondaryText");
            return (Criteria) this;
        }

        public Criteria andMainToneIsNull() {
            addCriterion("main_tone is null");
            return (Criteria) this;
        }

        public Criteria andMainToneIsNotNull() {
            addCriterion("main_tone is not null");
            return (Criteria) this;
        }

        public Criteria andMainToneEqualTo(String value) {
            addCriterion("main_tone =", value, "mainTone");
            return (Criteria) this;
        }

        public Criteria andMainToneNotEqualTo(String value) {
            addCriterion("main_tone <>", value, "mainTone");
            return (Criteria) this;
        }

        public Criteria andMainToneGreaterThan(String value) {
            addCriterion("main_tone >", value, "mainTone");
            return (Criteria) this;
        }

        public Criteria andMainToneGreaterThanOrEqualTo(String value) {
            addCriterion("main_tone >=", value, "mainTone");
            return (Criteria) this;
        }

        public Criteria andMainToneLessThan(String value) {
            addCriterion("main_tone <", value, "mainTone");
            return (Criteria) this;
        }

        public Criteria andMainToneLessThanOrEqualTo(String value) {
            addCriterion("main_tone <=", value, "mainTone");
            return (Criteria) this;
        }

        public Criteria andMainToneLike(String value) {
            addCriterion("main_tone like", value, "mainTone");
            return (Criteria) this;
        }

        public Criteria andMainToneNotLike(String value) {
            addCriterion("main_tone not like", value, "mainTone");
            return (Criteria) this;
        }

        public Criteria andMainToneIn(List<String> values) {
            addCriterion("main_tone in", values, "mainTone");
            return (Criteria) this;
        }

        public Criteria andMainToneNotIn(List<String> values) {
            addCriterion("main_tone not in", values, "mainTone");
            return (Criteria) this;
        }

        public Criteria andMainToneBetween(String value1, String value2) {
            addCriterion("main_tone between", value1, value2, "mainTone");
            return (Criteria) this;
        }

        public Criteria andMainToneNotBetween(String value1, String value2) {
            addCriterion("main_tone not between", value1, value2, "mainTone");
            return (Criteria) this;
        }

        public Criteria andLinkUrlIsNull() {
            addCriterion("link_url is null");
            return (Criteria) this;
        }

        public Criteria andLinkUrlIsNotNull() {
            addCriterion("link_url is not null");
            return (Criteria) this;
        }

        public Criteria andLinkUrlEqualTo(String value) {
            addCriterion("link_url =", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlNotEqualTo(String value) {
            addCriterion("link_url <>", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlGreaterThan(String value) {
            addCriterion("link_url >", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlGreaterThanOrEqualTo(String value) {
            addCriterion("link_url >=", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlLessThan(String value) {
            addCriterion("link_url <", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlLessThanOrEqualTo(String value) {
            addCriterion("link_url <=", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlLike(String value) {
            addCriterion("link_url like", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlNotLike(String value) {
            addCriterion("link_url not like", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlIn(List<String> values) {
            addCriterion("link_url in", values, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlNotIn(List<String> values) {
            addCriterion("link_url not in", values, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlBetween(String value1, String value2) {
            addCriterion("link_url between", value1, value2, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlNotBetween(String value1, String value2) {
            addCriterion("link_url not between", value1, value2, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_lightbox_source
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 18 10:54:32 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_lightbox_source
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}