package com.m2m.domain;

import java.util.Date;

public class AppLightboxSource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lightbox_source.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lightbox_source.image
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lightbox_source.main_text
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String mainText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lightbox_source.secondary_text
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String secondaryText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lightbox_source.main_tone
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String mainTone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lightbox_source.link_url
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lightbox_source.start_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lightbox_source.end_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_lightbox_source.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lightbox_source.id
     *
     * @return the value of app_lightbox_source.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lightbox_source.id
     *
     * @param id the value for app_lightbox_source.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lightbox_source.image
     *
     * @return the value of app_lightbox_source.image
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lightbox_source.image
     *
     * @param image the value for app_lightbox_source.image
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lightbox_source.main_text
     *
     * @return the value of app_lightbox_source.main_text
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getMainText() {
        return mainText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lightbox_source.main_text
     *
     * @param mainText the value for app_lightbox_source.main_text
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setMainText(String mainText) {
        this.mainText = mainText == null ? null : mainText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lightbox_source.secondary_text
     *
     * @return the value of app_lightbox_source.secondary_text
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getSecondaryText() {
        return secondaryText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lightbox_source.secondary_text
     *
     * @param secondaryText the value for app_lightbox_source.secondary_text
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setSecondaryText(String secondaryText) {
        this.secondaryText = secondaryText == null ? null : secondaryText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lightbox_source.main_tone
     *
     * @return the value of app_lightbox_source.main_tone
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getMainTone() {
        return mainTone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lightbox_source.main_tone
     *
     * @param mainTone the value for app_lightbox_source.main_tone
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setMainTone(String mainTone) {
        this.mainTone = mainTone == null ? null : mainTone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lightbox_source.link_url
     *
     * @return the value of app_lightbox_source.link_url
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lightbox_source.link_url
     *
     * @param linkUrl the value for app_lightbox_source.link_url
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lightbox_source.start_time
     *
     * @return the value of app_lightbox_source.start_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lightbox_source.start_time
     *
     * @param startTime the value for app_lightbox_source.start_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lightbox_source.end_time
     *
     * @return the value of app_lightbox_source.end_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lightbox_source.end_time
     *
     * @param endTime the value for app_lightbox_source.end_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_lightbox_source.status
     *
     * @return the value of app_lightbox_source.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_lightbox_source.status
     *
     * @param status the value for app_lightbox_source.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}