package com.m2m.domain;

public class BillboardDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billboard_details.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billboard_details.type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billboard_details.bid
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Long bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billboard_details.sort
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billboard_details.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billboard_details.id
     *
     * @return the value of billboard_details.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billboard_details.id
     *
     * @param id the value for billboard_details.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billboard_details.type
     *
     * @return the value of billboard_details.type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billboard_details.type
     *
     * @param type the value for billboard_details.type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billboard_details.bid
     *
     * @return the value of billboard_details.bid
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Long getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billboard_details.bid
     *
     * @param bid the value for billboard_details.bid
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setBid(Long bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billboard_details.sort
     *
     * @return the value of billboard_details.sort
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billboard_details.sort
     *
     * @param sort the value for billboard_details.sort
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billboard_details.status
     *
     * @return the value of billboard_details.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billboard_details.status
     *
     * @param status the value for billboard_details.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}