package com.m2m.domain;

import java.util.Date;

public class CmsFeature {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_feature.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_feature.feature_group_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer featureGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_feature.name
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_feature.created_at
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_feature.id
     *
     * @return the value of cms_feature.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_feature.id
     *
     * @param id the value for cms_feature.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_feature.feature_group_id
     *
     * @return the value of cms_feature.feature_group_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getFeatureGroupId() {
        return featureGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_feature.feature_group_id
     *
     * @param featureGroupId the value for cms_feature.feature_group_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setFeatureGroupId(Integer featureGroupId) {
        this.featureGroupId = featureGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_feature.name
     *
     * @return the value of cms_feature.name
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_feature.name
     *
     * @param name the value for cms_feature.name
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_feature.created_at
     *
     * @return the value of cms_feature.created_at
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_feature.created_at
     *
     * @param createdAt the value for cms_feature.created_at
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}