package com.m2m.domain;

import java.util.Date;

public class CmsUserLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_log.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_log.user_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_log.feature_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer featureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_log.created_at
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_log.id
     *
     * @return the value of cms_user_log.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_log.id
     *
     * @param id the value for cms_user_log.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_log.user_id
     *
     * @return the value of cms_user_log.user_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_log.user_id
     *
     * @param userId the value for cms_user_log.user_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_log.feature_id
     *
     * @return the value of cms_user_log.feature_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getFeatureId() {
        return featureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_log.feature_id
     *
     * @param featureId the value for cms_user_log.feature_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setFeatureId(Integer featureId) {
        this.featureId = featureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_log.created_at
     *
     * @return the value of cms_user_log.created_at
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_log.created_at
     *
     * @param createdAt the value for cms_user_log.created_at
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}