package com.m2m.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public ContentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Long value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Long value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Long value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Long value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Long value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Long value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Long> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Long> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Long value1, Long value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Long value1, Long value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andForwardCidIsNull() {
            addCriterion("forward_cid is null");
            return (Criteria) this;
        }

        public Criteria andForwardCidIsNotNull() {
            addCriterion("forward_cid is not null");
            return (Criteria) this;
        }

        public Criteria andForwardCidEqualTo(Long value) {
            addCriterion("forward_cid =", value, "forwardCid");
            return (Criteria) this;
        }

        public Criteria andForwardCidNotEqualTo(Long value) {
            addCriterion("forward_cid <>", value, "forwardCid");
            return (Criteria) this;
        }

        public Criteria andForwardCidGreaterThan(Long value) {
            addCriterion("forward_cid >", value, "forwardCid");
            return (Criteria) this;
        }

        public Criteria andForwardCidGreaterThanOrEqualTo(Long value) {
            addCriterion("forward_cid >=", value, "forwardCid");
            return (Criteria) this;
        }

        public Criteria andForwardCidLessThan(Long value) {
            addCriterion("forward_cid <", value, "forwardCid");
            return (Criteria) this;
        }

        public Criteria andForwardCidLessThanOrEqualTo(Long value) {
            addCriterion("forward_cid <=", value, "forwardCid");
            return (Criteria) this;
        }

        public Criteria andForwardCidIn(List<Long> values) {
            addCriterion("forward_cid in", values, "forwardCid");
            return (Criteria) this;
        }

        public Criteria andForwardCidNotIn(List<Long> values) {
            addCriterion("forward_cid not in", values, "forwardCid");
            return (Criteria) this;
        }

        public Criteria andForwardCidBetween(Long value1, Long value2) {
            addCriterion("forward_cid between", value1, value2, "forwardCid");
            return (Criteria) this;
        }

        public Criteria andForwardCidNotBetween(Long value1, Long value2) {
            addCriterion("forward_cid not between", value1, value2, "forwardCid");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andFeelingIsNull() {
            addCriterion("feeling is null");
            return (Criteria) this;
        }

        public Criteria andFeelingIsNotNull() {
            addCriterion("feeling is not null");
            return (Criteria) this;
        }

        public Criteria andFeelingEqualTo(String value) {
            addCriterion("feeling =", value, "feeling");
            return (Criteria) this;
        }

        public Criteria andFeelingNotEqualTo(String value) {
            addCriterion("feeling <>", value, "feeling");
            return (Criteria) this;
        }

        public Criteria andFeelingGreaterThan(String value) {
            addCriterion("feeling >", value, "feeling");
            return (Criteria) this;
        }

        public Criteria andFeelingGreaterThanOrEqualTo(String value) {
            addCriterion("feeling >=", value, "feeling");
            return (Criteria) this;
        }

        public Criteria andFeelingLessThan(String value) {
            addCriterion("feeling <", value, "feeling");
            return (Criteria) this;
        }

        public Criteria andFeelingLessThanOrEqualTo(String value) {
            addCriterion("feeling <=", value, "feeling");
            return (Criteria) this;
        }

        public Criteria andFeelingLike(String value) {
            addCriterion("feeling like", value, "feeling");
            return (Criteria) this;
        }

        public Criteria andFeelingNotLike(String value) {
            addCriterion("feeling not like", value, "feeling");
            return (Criteria) this;
        }

        public Criteria andFeelingIn(List<String> values) {
            addCriterion("feeling in", values, "feeling");
            return (Criteria) this;
        }

        public Criteria andFeelingNotIn(List<String> values) {
            addCriterion("feeling not in", values, "feeling");
            return (Criteria) this;
        }

        public Criteria andFeelingBetween(String value1, String value2) {
            addCriterion("feeling between", value1, value2, "feeling");
            return (Criteria) this;
        }

        public Criteria andFeelingNotBetween(String value1, String value2) {
            addCriterion("feeling not between", value1, value2, "feeling");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andConverImageIsNull() {
            addCriterion("conver_image is null");
            return (Criteria) this;
        }

        public Criteria andConverImageIsNotNull() {
            addCriterion("conver_image is not null");
            return (Criteria) this;
        }

        public Criteria andConverImageEqualTo(String value) {
            addCriterion("conver_image =", value, "converImage");
            return (Criteria) this;
        }

        public Criteria andConverImageNotEqualTo(String value) {
            addCriterion("conver_image <>", value, "converImage");
            return (Criteria) this;
        }

        public Criteria andConverImageGreaterThan(String value) {
            addCriterion("conver_image >", value, "converImage");
            return (Criteria) this;
        }

        public Criteria andConverImageGreaterThanOrEqualTo(String value) {
            addCriterion("conver_image >=", value, "converImage");
            return (Criteria) this;
        }

        public Criteria andConverImageLessThan(String value) {
            addCriterion("conver_image <", value, "converImage");
            return (Criteria) this;
        }

        public Criteria andConverImageLessThanOrEqualTo(String value) {
            addCriterion("conver_image <=", value, "converImage");
            return (Criteria) this;
        }

        public Criteria andConverImageLike(String value) {
            addCriterion("conver_image like", value, "converImage");
            return (Criteria) this;
        }

        public Criteria andConverImageNotLike(String value) {
            addCriterion("conver_image not like", value, "converImage");
            return (Criteria) this;
        }

        public Criteria andConverImageIn(List<String> values) {
            addCriterion("conver_image in", values, "converImage");
            return (Criteria) this;
        }

        public Criteria andConverImageNotIn(List<String> values) {
            addCriterion("conver_image not in", values, "converImage");
            return (Criteria) this;
        }

        public Criteria andConverImageBetween(String value1, String value2) {
            addCriterion("conver_image between", value1, value2, "converImage");
            return (Criteria) this;
        }

        public Criteria andConverImageNotBetween(String value1, String value2) {
            addCriterion("conver_image not between", value1, value2, "converImage");
            return (Criteria) this;
        }

        public Criteria andForwardTitleIsNull() {
            addCriterion("forward_title is null");
            return (Criteria) this;
        }

        public Criteria andForwardTitleIsNotNull() {
            addCriterion("forward_title is not null");
            return (Criteria) this;
        }

        public Criteria andForwardTitleEqualTo(String value) {
            addCriterion("forward_title =", value, "forwardTitle");
            return (Criteria) this;
        }

        public Criteria andForwardTitleNotEqualTo(String value) {
            addCriterion("forward_title <>", value, "forwardTitle");
            return (Criteria) this;
        }

        public Criteria andForwardTitleGreaterThan(String value) {
            addCriterion("forward_title >", value, "forwardTitle");
            return (Criteria) this;
        }

        public Criteria andForwardTitleGreaterThanOrEqualTo(String value) {
            addCriterion("forward_title >=", value, "forwardTitle");
            return (Criteria) this;
        }

        public Criteria andForwardTitleLessThan(String value) {
            addCriterion("forward_title <", value, "forwardTitle");
            return (Criteria) this;
        }

        public Criteria andForwardTitleLessThanOrEqualTo(String value) {
            addCriterion("forward_title <=", value, "forwardTitle");
            return (Criteria) this;
        }

        public Criteria andForwardTitleLike(String value) {
            addCriterion("forward_title like", value, "forwardTitle");
            return (Criteria) this;
        }

        public Criteria andForwardTitleNotLike(String value) {
            addCriterion("forward_title not like", value, "forwardTitle");
            return (Criteria) this;
        }

        public Criteria andForwardTitleIn(List<String> values) {
            addCriterion("forward_title in", values, "forwardTitle");
            return (Criteria) this;
        }

        public Criteria andForwardTitleNotIn(List<String> values) {
            addCriterion("forward_title not in", values, "forwardTitle");
            return (Criteria) this;
        }

        public Criteria andForwardTitleBetween(String value1, String value2) {
            addCriterion("forward_title between", value1, value2, "forwardTitle");
            return (Criteria) this;
        }

        public Criteria andForwardTitleNotBetween(String value1, String value2) {
            addCriterion("forward_title not between", value1, value2, "forwardTitle");
            return (Criteria) this;
        }

        public Criteria andForwardUrlIsNull() {
            addCriterion("forward_url is null");
            return (Criteria) this;
        }

        public Criteria andForwardUrlIsNotNull() {
            addCriterion("forward_url is not null");
            return (Criteria) this;
        }

        public Criteria andForwardUrlEqualTo(String value) {
            addCriterion("forward_url =", value, "forwardUrl");
            return (Criteria) this;
        }

        public Criteria andForwardUrlNotEqualTo(String value) {
            addCriterion("forward_url <>", value, "forwardUrl");
            return (Criteria) this;
        }

        public Criteria andForwardUrlGreaterThan(String value) {
            addCriterion("forward_url >", value, "forwardUrl");
            return (Criteria) this;
        }

        public Criteria andForwardUrlGreaterThanOrEqualTo(String value) {
            addCriterion("forward_url >=", value, "forwardUrl");
            return (Criteria) this;
        }

        public Criteria andForwardUrlLessThan(String value) {
            addCriterion("forward_url <", value, "forwardUrl");
            return (Criteria) this;
        }

        public Criteria andForwardUrlLessThanOrEqualTo(String value) {
            addCriterion("forward_url <=", value, "forwardUrl");
            return (Criteria) this;
        }

        public Criteria andForwardUrlLike(String value) {
            addCriterion("forward_url like", value, "forwardUrl");
            return (Criteria) this;
        }

        public Criteria andForwardUrlNotLike(String value) {
            addCriterion("forward_url not like", value, "forwardUrl");
            return (Criteria) this;
        }

        public Criteria andForwardUrlIn(List<String> values) {
            addCriterion("forward_url in", values, "forwardUrl");
            return (Criteria) this;
        }

        public Criteria andForwardUrlNotIn(List<String> values) {
            addCriterion("forward_url not in", values, "forwardUrl");
            return (Criteria) this;
        }

        public Criteria andForwardUrlBetween(String value1, String value2) {
            addCriterion("forward_url between", value1, value2, "forwardUrl");
            return (Criteria) this;
        }

        public Criteria andForwardUrlNotBetween(String value1, String value2) {
            addCriterion("forward_url not between", value1, value2, "forwardUrl");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNull() {
            addCriterion("content_type is null");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNotNull() {
            addCriterion("content_type is not null");
            return (Criteria) this;
        }

        public Criteria andContentTypeEqualTo(Integer value) {
            addCriterion("content_type =", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotEqualTo(Integer value) {
            addCriterion("content_type <>", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThan(Integer value) {
            addCriterion("content_type >", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("content_type >=", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThan(Integer value) {
            addCriterion("content_type <", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThanOrEqualTo(Integer value) {
            addCriterion("content_type <=", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeIn(List<Integer> values) {
            addCriterion("content_type in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotIn(List<Integer> values) {
            addCriterion("content_type not in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeBetween(Integer value1, Integer value2) {
            addCriterion("content_type between", value1, value2, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("content_type not between", value1, value2, "contentType");
            return (Criteria) this;
        }

        public Criteria andThumbnailIsNull() {
            addCriterion("thumbnail is null");
            return (Criteria) this;
        }

        public Criteria andThumbnailIsNotNull() {
            addCriterion("thumbnail is not null");
            return (Criteria) this;
        }

        public Criteria andThumbnailEqualTo(String value) {
            addCriterion("thumbnail =", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotEqualTo(String value) {
            addCriterion("thumbnail <>", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailGreaterThan(String value) {
            addCriterion("thumbnail >", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailGreaterThanOrEqualTo(String value) {
            addCriterion("thumbnail >=", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailLessThan(String value) {
            addCriterion("thumbnail <", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailLessThanOrEqualTo(String value) {
            addCriterion("thumbnail <=", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailLike(String value) {
            addCriterion("thumbnail like", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotLike(String value) {
            addCriterion("thumbnail not like", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailIn(List<String> values) {
            addCriterion("thumbnail in", values, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotIn(List<String> values) {
            addCriterion("thumbnail not in", values, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailBetween(String value1, String value2) {
            addCriterion("thumbnail between", value1, value2, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotBetween(String value1, String value2) {
            addCriterion("thumbnail not between", value1, value2, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andHotValueIsNull() {
            addCriterion("hot_value is null");
            return (Criteria) this;
        }

        public Criteria andHotValueIsNotNull() {
            addCriterion("hot_value is not null");
            return (Criteria) this;
        }

        public Criteria andHotValueEqualTo(Integer value) {
            addCriterion("hot_value =", value, "hotValue");
            return (Criteria) this;
        }

        public Criteria andHotValueNotEqualTo(Integer value) {
            addCriterion("hot_value <>", value, "hotValue");
            return (Criteria) this;
        }

        public Criteria andHotValueGreaterThan(Integer value) {
            addCriterion("hot_value >", value, "hotValue");
            return (Criteria) this;
        }

        public Criteria andHotValueGreaterThanOrEqualTo(Integer value) {
            addCriterion("hot_value >=", value, "hotValue");
            return (Criteria) this;
        }

        public Criteria andHotValueLessThan(Integer value) {
            addCriterion("hot_value <", value, "hotValue");
            return (Criteria) this;
        }

        public Criteria andHotValueLessThanOrEqualTo(Integer value) {
            addCriterion("hot_value <=", value, "hotValue");
            return (Criteria) this;
        }

        public Criteria andHotValueIn(List<Integer> values) {
            addCriterion("hot_value in", values, "hotValue");
            return (Criteria) this;
        }

        public Criteria andHotValueNotIn(List<Integer> values) {
            addCriterion("hot_value not in", values, "hotValue");
            return (Criteria) this;
        }

        public Criteria andHotValueBetween(Integer value1, Integer value2) {
            addCriterion("hot_value between", value1, value2, "hotValue");
            return (Criteria) this;
        }

        public Criteria andHotValueNotBetween(Integer value1, Integer value2) {
            addCriterion("hot_value not between", value1, value2, "hotValue");
            return (Criteria) this;
        }

        public Criteria andPersonCountIsNull() {
            addCriterion("person_count is null");
            return (Criteria) this;
        }

        public Criteria andPersonCountIsNotNull() {
            addCriterion("person_count is not null");
            return (Criteria) this;
        }

        public Criteria andPersonCountEqualTo(Integer value) {
            addCriterion("person_count =", value, "personCount");
            return (Criteria) this;
        }

        public Criteria andPersonCountNotEqualTo(Integer value) {
            addCriterion("person_count <>", value, "personCount");
            return (Criteria) this;
        }

        public Criteria andPersonCountGreaterThan(Integer value) {
            addCriterion("person_count >", value, "personCount");
            return (Criteria) this;
        }

        public Criteria andPersonCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("person_count >=", value, "personCount");
            return (Criteria) this;
        }

        public Criteria andPersonCountLessThan(Integer value) {
            addCriterion("person_count <", value, "personCount");
            return (Criteria) this;
        }

        public Criteria andPersonCountLessThanOrEqualTo(Integer value) {
            addCriterion("person_count <=", value, "personCount");
            return (Criteria) this;
        }

        public Criteria andPersonCountIn(List<Integer> values) {
            addCriterion("person_count in", values, "personCount");
            return (Criteria) this;
        }

        public Criteria andPersonCountNotIn(List<Integer> values) {
            addCriterion("person_count not in", values, "personCount");
            return (Criteria) this;
        }

        public Criteria andPersonCountBetween(Integer value1, Integer value2) {
            addCriterion("person_count between", value1, value2, "personCount");
            return (Criteria) this;
        }

        public Criteria andPersonCountNotBetween(Integer value1, Integer value2) {
            addCriterion("person_count not between", value1, value2, "personCount");
            return (Criteria) this;
        }

        public Criteria andReviewCountIsNull() {
            addCriterion("review_count is null");
            return (Criteria) this;
        }

        public Criteria andReviewCountIsNotNull() {
            addCriterion("review_count is not null");
            return (Criteria) this;
        }

        public Criteria andReviewCountEqualTo(Integer value) {
            addCriterion("review_count =", value, "reviewCount");
            return (Criteria) this;
        }

        public Criteria andReviewCountNotEqualTo(Integer value) {
            addCriterion("review_count <>", value, "reviewCount");
            return (Criteria) this;
        }

        public Criteria andReviewCountGreaterThan(Integer value) {
            addCriterion("review_count >", value, "reviewCount");
            return (Criteria) this;
        }

        public Criteria andReviewCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("review_count >=", value, "reviewCount");
            return (Criteria) this;
        }

        public Criteria andReviewCountLessThan(Integer value) {
            addCriterion("review_count <", value, "reviewCount");
            return (Criteria) this;
        }

        public Criteria andReviewCountLessThanOrEqualTo(Integer value) {
            addCriterion("review_count <=", value, "reviewCount");
            return (Criteria) this;
        }

        public Criteria andReviewCountIn(List<Integer> values) {
            addCriterion("review_count in", values, "reviewCount");
            return (Criteria) this;
        }

        public Criteria andReviewCountNotIn(List<Integer> values) {
            addCriterion("review_count not in", values, "reviewCount");
            return (Criteria) this;
        }

        public Criteria andReviewCountBetween(Integer value1, Integer value2) {
            addCriterion("review_count between", value1, value2, "reviewCount");
            return (Criteria) this;
        }

        public Criteria andReviewCountNotBetween(Integer value1, Integer value2) {
            addCriterion("review_count not between", value1, value2, "reviewCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountIsNull() {
            addCriterion("like_count is null");
            return (Criteria) this;
        }

        public Criteria andLikeCountIsNotNull() {
            addCriterion("like_count is not null");
            return (Criteria) this;
        }

        public Criteria andLikeCountEqualTo(Integer value) {
            addCriterion("like_count =", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountNotEqualTo(Integer value) {
            addCriterion("like_count <>", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountGreaterThan(Integer value) {
            addCriterion("like_count >", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("like_count >=", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountLessThan(Integer value) {
            addCriterion("like_count <", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountLessThanOrEqualTo(Integer value) {
            addCriterion("like_count <=", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountIn(List<Integer> values) {
            addCriterion("like_count in", values, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountNotIn(List<Integer> values) {
            addCriterion("like_count not in", values, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountBetween(Integer value1, Integer value2) {
            addCriterion("like_count between", value1, value2, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("like_count not between", value1, value2, "likeCount");
            return (Criteria) this;
        }

        public Criteria andFavoriteCountIsNull() {
            addCriterion("favorite_count is null");
            return (Criteria) this;
        }

        public Criteria andFavoriteCountIsNotNull() {
            addCriterion("favorite_count is not null");
            return (Criteria) this;
        }

        public Criteria andFavoriteCountEqualTo(Integer value) {
            addCriterion("favorite_count =", value, "favoriteCount");
            return (Criteria) this;
        }

        public Criteria andFavoriteCountNotEqualTo(Integer value) {
            addCriterion("favorite_count <>", value, "favoriteCount");
            return (Criteria) this;
        }

        public Criteria andFavoriteCountGreaterThan(Integer value) {
            addCriterion("favorite_count >", value, "favoriteCount");
            return (Criteria) this;
        }

        public Criteria andFavoriteCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("favorite_count >=", value, "favoriteCount");
            return (Criteria) this;
        }

        public Criteria andFavoriteCountLessThan(Integer value) {
            addCriterion("favorite_count <", value, "favoriteCount");
            return (Criteria) this;
        }

        public Criteria andFavoriteCountLessThanOrEqualTo(Integer value) {
            addCriterion("favorite_count <=", value, "favoriteCount");
            return (Criteria) this;
        }

        public Criteria andFavoriteCountIn(List<Integer> values) {
            addCriterion("favorite_count in", values, "favoriteCount");
            return (Criteria) this;
        }

        public Criteria andFavoriteCountNotIn(List<Integer> values) {
            addCriterion("favorite_count not in", values, "favoriteCount");
            return (Criteria) this;
        }

        public Criteria andFavoriteCountBetween(Integer value1, Integer value2) {
            addCriterion("favorite_count between", value1, value2, "favoriteCount");
            return (Criteria) this;
        }

        public Criteria andFavoriteCountNotBetween(Integer value1, Integer value2) {
            addCriterion("favorite_count not between", value1, value2, "favoriteCount");
            return (Criteria) this;
        }

        public Criteria andReadCountIsNull() {
            addCriterion("read_count is null");
            return (Criteria) this;
        }

        public Criteria andReadCountIsNotNull() {
            addCriterion("read_count is not null");
            return (Criteria) this;
        }

        public Criteria andReadCountEqualTo(Integer value) {
            addCriterion("read_count =", value, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountNotEqualTo(Integer value) {
            addCriterion("read_count <>", value, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountGreaterThan(Integer value) {
            addCriterion("read_count >", value, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("read_count >=", value, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountLessThan(Integer value) {
            addCriterion("read_count <", value, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountLessThanOrEqualTo(Integer value) {
            addCriterion("read_count <=", value, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountIn(List<Integer> values) {
            addCriterion("read_count in", values, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountNotIn(List<Integer> values) {
            addCriterion("read_count not in", values, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountBetween(Integer value1, Integer value2) {
            addCriterion("read_count between", value1, value2, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountNotBetween(Integer value1, Integer value2) {
            addCriterion("read_count not between", value1, value2, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountDummyIsNull() {
            addCriterion("read_count_dummy is null");
            return (Criteria) this;
        }

        public Criteria andReadCountDummyIsNotNull() {
            addCriterion("read_count_dummy is not null");
            return (Criteria) this;
        }

        public Criteria andReadCountDummyEqualTo(Integer value) {
            addCriterion("read_count_dummy =", value, "readCountDummy");
            return (Criteria) this;
        }

        public Criteria andReadCountDummyNotEqualTo(Integer value) {
            addCriterion("read_count_dummy <>", value, "readCountDummy");
            return (Criteria) this;
        }

        public Criteria andReadCountDummyGreaterThan(Integer value) {
            addCriterion("read_count_dummy >", value, "readCountDummy");
            return (Criteria) this;
        }

        public Criteria andReadCountDummyGreaterThanOrEqualTo(Integer value) {
            addCriterion("read_count_dummy >=", value, "readCountDummy");
            return (Criteria) this;
        }

        public Criteria andReadCountDummyLessThan(Integer value) {
            addCriterion("read_count_dummy <", value, "readCountDummy");
            return (Criteria) this;
        }

        public Criteria andReadCountDummyLessThanOrEqualTo(Integer value) {
            addCriterion("read_count_dummy <=", value, "readCountDummy");
            return (Criteria) this;
        }

        public Criteria andReadCountDummyIn(List<Integer> values) {
            addCriterion("read_count_dummy in", values, "readCountDummy");
            return (Criteria) this;
        }

        public Criteria andReadCountDummyNotIn(List<Integer> values) {
            addCriterion("read_count_dummy not in", values, "readCountDummy");
            return (Criteria) this;
        }

        public Criteria andReadCountDummyBetween(Integer value1, Integer value2) {
            addCriterion("read_count_dummy between", value1, value2, "readCountDummy");
            return (Criteria) this;
        }

        public Criteria andReadCountDummyNotBetween(Integer value1, Integer value2) {
            addCriterion("read_count_dummy not between", value1, value2, "readCountDummy");
            return (Criteria) this;
        }

        public Criteria andIsTopIsNull() {
            addCriterion("is_top is null");
            return (Criteria) this;
        }

        public Criteria andIsTopIsNotNull() {
            addCriterion("is_top is not null");
            return (Criteria) this;
        }

        public Criteria andIsTopEqualTo(Integer value) {
            addCriterion("is_top =", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopNotEqualTo(Integer value) {
            addCriterion("is_top <>", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopGreaterThan(Integer value) {
            addCriterion("is_top >", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_top >=", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopLessThan(Integer value) {
            addCriterion("is_top <", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopLessThanOrEqualTo(Integer value) {
            addCriterion("is_top <=", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopIn(List<Integer> values) {
            addCriterion("is_top in", values, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopNotIn(List<Integer> values) {
            addCriterion("is_top not in", values, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopBetween(Integer value1, Integer value2) {
            addCriterion("is_top between", value1, value2, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopNotBetween(Integer value1, Integer value2) {
            addCriterion("is_top not between", value1, value2, "isTop");
            return (Criteria) this;
        }

        public Criteria andAuthorizationIsNull() {
            addCriterion("authorization is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationIsNotNull() {
            addCriterion("authorization is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationEqualTo(Integer value) {
            addCriterion("authorization =", value, "authorization");
            return (Criteria) this;
        }

        public Criteria andAuthorizationNotEqualTo(Integer value) {
            addCriterion("authorization <>", value, "authorization");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGreaterThan(Integer value) {
            addCriterion("authorization >", value, "authorization");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGreaterThanOrEqualTo(Integer value) {
            addCriterion("authorization >=", value, "authorization");
            return (Criteria) this;
        }

        public Criteria andAuthorizationLessThan(Integer value) {
            addCriterion("authorization <", value, "authorization");
            return (Criteria) this;
        }

        public Criteria andAuthorizationLessThanOrEqualTo(Integer value) {
            addCriterion("authorization <=", value, "authorization");
            return (Criteria) this;
        }

        public Criteria andAuthorizationIn(List<Integer> values) {
            addCriterion("authorization in", values, "authorization");
            return (Criteria) this;
        }

        public Criteria andAuthorizationNotIn(List<Integer> values) {
            addCriterion("authorization not in", values, "authorization");
            return (Criteria) this;
        }

        public Criteria andAuthorizationBetween(Integer value1, Integer value2) {
            addCriterion("authorization between", value1, value2, "authorization");
            return (Criteria) this;
        }

        public Criteria andAuthorizationNotBetween(Integer value1, Integer value2) {
            addCriterion("authorization not between", value1, value2, "authorization");
            return (Criteria) this;
        }

        public Criteria andRightsIsNull() {
            addCriterion("rights is null");
            return (Criteria) this;
        }

        public Criteria andRightsIsNotNull() {
            addCriterion("rights is not null");
            return (Criteria) this;
        }

        public Criteria andRightsEqualTo(Integer value) {
            addCriterion("rights =", value, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsNotEqualTo(Integer value) {
            addCriterion("rights <>", value, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsGreaterThan(Integer value) {
            addCriterion("rights >", value, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsGreaterThanOrEqualTo(Integer value) {
            addCriterion("rights >=", value, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsLessThan(Integer value) {
            addCriterion("rights <", value, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsLessThanOrEqualTo(Integer value) {
            addCriterion("rights <=", value, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsIn(List<Integer> values) {
            addCriterion("rights in", values, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsNotIn(List<Integer> values) {
            addCriterion("rights not in", values, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsBetween(Integer value1, Integer value2) {
            addCriterion("rights between", value1, value2, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsNotBetween(Integer value1, Integer value2) {
            addCriterion("rights not between", value1, value2, "rights");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("author is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("author is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(Integer value) {
            addCriterion("author =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(Integer value) {
            addCriterion("author <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(Integer value) {
            addCriterion("author >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(Integer value) {
            addCriterion("author >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(Integer value) {
            addCriterion("author <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(Integer value) {
            addCriterion("author <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<Integer> values) {
            addCriterion("author in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<Integer> values) {
            addCriterion("author not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(Integer value1, Integer value2) {
            addCriterion("author between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(Integer value1, Integer value2) {
            addCriterion("author not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNull() {
            addCriterion("update_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNotNull() {
            addCriterion("update_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdEqualTo(Long value) {
            addCriterion("update_id =", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotEqualTo(Long value) {
            addCriterion("update_id <>", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThan(Long value) {
            addCriterion("update_id >", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("update_id >=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThan(Long value) {
            addCriterion("update_id <", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThanOrEqualTo(Long value) {
            addCriterion("update_id <=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIn(List<Long> values) {
            addCriterion("update_id in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotIn(List<Long> values) {
            addCriterion("update_id not in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdBetween(Long value1, Long value2) {
            addCriterion("update_id between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotBetween(Long value1, Long value2) {
            addCriterion("update_id not between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUgcStatusIsNull() {
            addCriterion("ugc_status is null");
            return (Criteria) this;
        }

        public Criteria andUgcStatusIsNotNull() {
            addCriterion("ugc_status is not null");
            return (Criteria) this;
        }

        public Criteria andUgcStatusEqualTo(Integer value) {
            addCriterion("ugc_status =", value, "ugcStatus");
            return (Criteria) this;
        }

        public Criteria andUgcStatusNotEqualTo(Integer value) {
            addCriterion("ugc_status <>", value, "ugcStatus");
            return (Criteria) this;
        }

        public Criteria andUgcStatusGreaterThan(Integer value) {
            addCriterion("ugc_status >", value, "ugcStatus");
            return (Criteria) this;
        }

        public Criteria andUgcStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("ugc_status >=", value, "ugcStatus");
            return (Criteria) this;
        }

        public Criteria andUgcStatusLessThan(Integer value) {
            addCriterion("ugc_status <", value, "ugcStatus");
            return (Criteria) this;
        }

        public Criteria andUgcStatusLessThanOrEqualTo(Integer value) {
            addCriterion("ugc_status <=", value, "ugcStatus");
            return (Criteria) this;
        }

        public Criteria andUgcStatusIn(List<Integer> values) {
            addCriterion("ugc_status in", values, "ugcStatus");
            return (Criteria) this;
        }

        public Criteria andUgcStatusNotIn(List<Integer> values) {
            addCriterion("ugc_status not in", values, "ugcStatus");
            return (Criteria) this;
        }

        public Criteria andUgcStatusBetween(Integer value1, Integer value2) {
            addCriterion("ugc_status between", value1, value2, "ugcStatus");
            return (Criteria) this;
        }

        public Criteria andUgcStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("ugc_status not between", value1, value2, "ugcStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 18 10:54:32 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}