package com.m2m.domain;

public class EmotionPack {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack.name
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack.cover
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack.emoji_type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer emojiType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack.version
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack.p_version
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer pVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack.extra
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String extra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack.order_num
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack.is_valid
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack.id
     *
     * @return the value of emotion_pack.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack.id
     *
     * @param id the value for emotion_pack.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack.name
     *
     * @return the value of emotion_pack.name
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack.name
     *
     * @param name the value for emotion_pack.name
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack.cover
     *
     * @return the value of emotion_pack.cover
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack.cover
     *
     * @param cover the value for emotion_pack.cover
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack.emoji_type
     *
     * @return the value of emotion_pack.emoji_type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getEmojiType() {
        return emojiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack.emoji_type
     *
     * @param emojiType the value for emotion_pack.emoji_type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setEmojiType(Integer emojiType) {
        this.emojiType = emojiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack.version
     *
     * @return the value of emotion_pack.version
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack.version
     *
     * @param version the value for emotion_pack.version
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack.p_version
     *
     * @return the value of emotion_pack.p_version
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getpVersion() {
        return pVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack.p_version
     *
     * @param pVersion the value for emotion_pack.p_version
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setpVersion(Integer pVersion) {
        this.pVersion = pVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack.extra
     *
     * @return the value of emotion_pack.extra
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack.extra
     *
     * @param extra the value for emotion_pack.extra
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setExtra(String extra) {
        this.extra = extra == null ? null : extra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack.order_num
     *
     * @return the value of emotion_pack.order_num
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack.order_num
     *
     * @param orderNum the value for emotion_pack.order_num
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack.is_valid
     *
     * @return the value of emotion_pack.is_valid
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack.is_valid
     *
     * @param isValid the value for emotion_pack.is_valid
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}