package com.m2m.domain;

public class EmotionPackDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack_detail.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack_detail.pack_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer packId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack_detail.title
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack_detail.image
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack_detail.thumb
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String thumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack_detail.w
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer w;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack_detail.h
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer h;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack_detail.thumb_w
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer thumbW;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack_detail.thumb_h
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer thumbH;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack_detail.extra
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String extra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_pack_detail.order_num
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer orderNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack_detail.id
     *
     * @return the value of emotion_pack_detail.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack_detail.id
     *
     * @param id the value for emotion_pack_detail.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack_detail.pack_id
     *
     * @return the value of emotion_pack_detail.pack_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getPackId() {
        return packId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack_detail.pack_id
     *
     * @param packId the value for emotion_pack_detail.pack_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setPackId(Integer packId) {
        this.packId = packId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack_detail.title
     *
     * @return the value of emotion_pack_detail.title
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack_detail.title
     *
     * @param title the value for emotion_pack_detail.title
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack_detail.image
     *
     * @return the value of emotion_pack_detail.image
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack_detail.image
     *
     * @param image the value for emotion_pack_detail.image
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack_detail.thumb
     *
     * @return the value of emotion_pack_detail.thumb
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getThumb() {
        return thumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack_detail.thumb
     *
     * @param thumb the value for emotion_pack_detail.thumb
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setThumb(String thumb) {
        this.thumb = thumb == null ? null : thumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack_detail.w
     *
     * @return the value of emotion_pack_detail.w
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getW() {
        return w;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack_detail.w
     *
     * @param w the value for emotion_pack_detail.w
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setW(Integer w) {
        this.w = w;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack_detail.h
     *
     * @return the value of emotion_pack_detail.h
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getH() {
        return h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack_detail.h
     *
     * @param h the value for emotion_pack_detail.h
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setH(Integer h) {
        this.h = h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack_detail.thumb_w
     *
     * @return the value of emotion_pack_detail.thumb_w
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getThumbW() {
        return thumbW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack_detail.thumb_w
     *
     * @param thumbW the value for emotion_pack_detail.thumb_w
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setThumbW(Integer thumbW) {
        this.thumbW = thumbW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack_detail.thumb_h
     *
     * @return the value of emotion_pack_detail.thumb_h
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getThumbH() {
        return thumbH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack_detail.thumb_h
     *
     * @param thumbH the value for emotion_pack_detail.thumb_h
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setThumbH(Integer thumbH) {
        this.thumbH = thumbH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack_detail.extra
     *
     * @return the value of emotion_pack_detail.extra
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack_detail.extra
     *
     * @param extra the value for emotion_pack_detail.extra
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setExtra(String extra) {
        this.extra = extra == null ? null : extra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_pack_detail.order_num
     *
     * @return the value of emotion_pack_detail.order_num
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_pack_detail.order_num
     *
     * @param orderNum the value for emotion_pack_detail.order_num
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
}