package com.m2m.domain;

import java.util.Date;

public class GiftInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_info.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_info.name
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_info.image
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_info.price
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_info.add_price
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer addPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_info.image_width
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer imageWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_info.image_height
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer imageHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_info.gif_image
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String gifImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_info.play_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer playTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_info.sort_number
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer sortNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_info.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_info.create_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_info.id
     *
     * @return the value of gift_info.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_info.id
     *
     * @param id the value for gift_info.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_info.name
     *
     * @return the value of gift_info.name
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_info.name
     *
     * @param name the value for gift_info.name
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_info.image
     *
     * @return the value of gift_info.image
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_info.image
     *
     * @param image the value for gift_info.image
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_info.price
     *
     * @return the value of gift_info.price
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_info.price
     *
     * @param price the value for gift_info.price
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_info.add_price
     *
     * @return the value of gift_info.add_price
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getAddPrice() {
        return addPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_info.add_price
     *
     * @param addPrice the value for gift_info.add_price
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setAddPrice(Integer addPrice) {
        this.addPrice = addPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_info.image_width
     *
     * @return the value of gift_info.image_width
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getImageWidth() {
        return imageWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_info.image_width
     *
     * @param imageWidth the value for gift_info.image_width
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setImageWidth(Integer imageWidth) {
        this.imageWidth = imageWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_info.image_height
     *
     * @return the value of gift_info.image_height
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getImageHeight() {
        return imageHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_info.image_height
     *
     * @param imageHeight the value for gift_info.image_height
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setImageHeight(Integer imageHeight) {
        this.imageHeight = imageHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_info.gif_image
     *
     * @return the value of gift_info.gif_image
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getGifImage() {
        return gifImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_info.gif_image
     *
     * @param gifImage the value for gift_info.gif_image
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setGifImage(String gifImage) {
        this.gifImage = gifImage == null ? null : gifImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_info.play_time
     *
     * @return the value of gift_info.play_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getPlayTime() {
        return playTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_info.play_time
     *
     * @param playTime the value for gift_info.play_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setPlayTime(Integer playTime) {
        this.playTime = playTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_info.sort_number
     *
     * @return the value of gift_info.sort_number
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getSortNumber() {
        return sortNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_info.sort_number
     *
     * @param sortNumber the value for gift_info.sort_number
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setSortNumber(Integer sortNumber) {
        this.sortNumber = sortNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_info.status
     *
     * @return the value of gift_info.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_info.status
     *
     * @param status the value for gift_info.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_info.create_time
     *
     * @return the value of gift_info.create_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_info.create_time
     *
     * @param createTime the value for gift_info.create_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}