package com.m2m.domain;

import java.util.Date;

public class Topic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.uid
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.live_image
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String liveImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.create_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.update_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.long_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Long longTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.qrcode
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String qrcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.core_circle
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String coreCircle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.ce_audit_type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer ceAuditType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.ac_audit_type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer acAuditType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.ac_publish_type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer acPublishType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.rights
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer rights;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.summary
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.sub_type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer subType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.price
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.listing_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Date listingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.out_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Date outTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.category_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.auto_join_core
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer autoJoinCore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.only_friend
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    private Integer onlyFriend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.uid
     *
     * @return the value of topic.uid
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.uid
     *
     * @param uid the value for topic.uid
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.live_image
     *
     * @return the value of topic.live_image
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getLiveImage() {
        return liveImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.live_image
     *
     * @param liveImage the value for topic.live_image
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setLiveImage(String liveImage) {
        this.liveImage = liveImage == null ? null : liveImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.status
     *
     * @return the value of topic.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.status
     *
     * @param status the value for topic.status
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.create_time
     *
     * @return the value of topic.create_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.create_time
     *
     * @param createTime the value for topic.create_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.update_time
     *
     * @return the value of topic.update_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.update_time
     *
     * @param updateTime the value for topic.update_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.long_time
     *
     * @return the value of topic.long_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Long getLongTime() {
        return longTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.long_time
     *
     * @param longTime the value for topic.long_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setLongTime(Long longTime) {
        this.longTime = longTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.qrcode
     *
     * @return the value of topic.qrcode
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.qrcode
     *
     * @param qrcode the value for topic.qrcode
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode == null ? null : qrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.core_circle
     *
     * @return the value of topic.core_circle
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getCoreCircle() {
        return coreCircle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.core_circle
     *
     * @param coreCircle the value for topic.core_circle
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setCoreCircle(String coreCircle) {
        this.coreCircle = coreCircle == null ? null : coreCircle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.type
     *
     * @return the value of topic.type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.type
     *
     * @param type the value for topic.type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.ce_audit_type
     *
     * @return the value of topic.ce_audit_type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getCeAuditType() {
        return ceAuditType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.ce_audit_type
     *
     * @param ceAuditType the value for topic.ce_audit_type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setCeAuditType(Integer ceAuditType) {
        this.ceAuditType = ceAuditType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.ac_audit_type
     *
     * @return the value of topic.ac_audit_type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getAcAuditType() {
        return acAuditType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.ac_audit_type
     *
     * @param acAuditType the value for topic.ac_audit_type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setAcAuditType(Integer acAuditType) {
        this.acAuditType = acAuditType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.ac_publish_type
     *
     * @return the value of topic.ac_publish_type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getAcPublishType() {
        return acPublishType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.ac_publish_type
     *
     * @param acPublishType the value for topic.ac_publish_type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setAcPublishType(Integer acPublishType) {
        this.acPublishType = acPublishType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.rights
     *
     * @return the value of topic.rights
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getRights() {
        return rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.rights
     *
     * @param rights the value for topic.rights
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setRights(Integer rights) {
        this.rights = rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.summary
     *
     * @return the value of topic.summary
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.summary
     *
     * @param summary the value for topic.summary
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.sub_type
     *
     * @return the value of topic.sub_type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getSubType() {
        return subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.sub_type
     *
     * @param subType the value for topic.sub_type
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setSubType(Integer subType) {
        this.subType = subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.price
     *
     * @return the value of topic.price
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.price
     *
     * @param price the value for topic.price
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.listing_time
     *
     * @return the value of topic.listing_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Date getListingTime() {
        return listingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.listing_time
     *
     * @param listingTime the value for topic.listing_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setListingTime(Date listingTime) {
        this.listingTime = listingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.out_time
     *
     * @return the value of topic.out_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.out_time
     *
     * @param outTime the value for topic.out_time
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.category_id
     *
     * @return the value of topic.category_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.category_id
     *
     * @param categoryId the value for topic.category_id
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.auto_join_core
     *
     * @return the value of topic.auto_join_core
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getAutoJoinCore() {
        return autoJoinCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.auto_join_core
     *
     * @param autoJoinCore the value for topic.auto_join_core
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setAutoJoinCore(Integer autoJoinCore) {
        this.autoJoinCore = autoJoinCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.only_friend
     *
     * @return the value of topic.only_friend
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public Integer getOnlyFriend() {
        return onlyFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.only_friend
     *
     * @param onlyFriend the value for topic.only_friend
     *
     * @mbg.generated Thu Jan 18 10:54:32 CST 2018
     */
    public void setOnlyFriend(Integer onlyFriend) {
        this.onlyFriend = onlyFriend;
    }
}